apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gratibot2-db
spec:
  selector:
    matchLabels:
      app: gratibot2-db
  serviceName: "gratibot2-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: gratibot2-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image }}"
        command: --init-file /data/db/init.sql
        env:
          - MYSQL_ROOT_PASSWORD=password
        strategy:
          type: recreate
        volumeMounts:
        - mountPath: /data/db
          name: mysql-data
        - mountPath: /data/init
          name: mysql-initdb
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClassName | default "gp2" }}
      resources:
        requests:
          storage: "2Gi"
